import { existsSync } from 'fs';
import pc from 'picocolors';
import { select } from '@inquirer/prompts';
import { loadRegistry, searchEntries, findByPath } from '../registry.js';
import { isInsideGitRepo, getRepoRoot } from '../git.js';
import type { RegistryEntry } from '../types.js';

/**
 * Resolve target entry from query or CWD.
 */
async function resolveEntry(query: string | undefined): Promise<RegistryEntry> {
  const registry = loadRegistry();

  if (query) {
    const matches = searchEntries(registry, query);
    if (matches.length === 0) {
      process.stderr.write(`No repositories match query: ${query}\n`);
      process.exit(1);
    }
    if (matches.length === 1) return matches[0];
    return await select<RegistryEntry>({
      message: 'Multiple repositories matched. Select one:',
      choices: matches.map(e => ({
        name: `${e.repoName} (${e.localPath})`,
        value: e,
        description: `Last updated: ${e.lastUpdated}`,
      })),
    }, { output: process.stderr });
  }

  if (!isInsideGitRepo()) {
    process.stderr.write('Not inside a git repository. Provide a query or run from within a registered repo.\n');
    process.exit(1);
  }

  const repoRoot = getRepoRoot();
  const entry = findByPath(registry, repoRoot);
  if (!entry) {
    process.stderr.write('Current repository is not registered. Run \'gitter scan\' first.\n');
    process.exit(1);
  }
  return entry;
}

/**
 * Handler for `gitter info [query]` command.
 * If no query is provided and CWD is inside a registered repo, uses that repo.
 */
export async function infoCommand(query: string | undefined): Promise<void> {
  const entry = await resolveEntry(query);

  const pathExists = existsSync(entry.localPath);
  const pathDisplay = pathExists
    ? entry.localPath
    : `${entry.localPath} ${pc.red('[MISSING]')}`;

  console.log(`\n${pc.bold('Repository Name:')}  ${entry.repoName}`);
  console.log(`${pc.bold('Local Path:')}       ${pathDisplay}`);

  // Remotes
  console.log(`${pc.bold('Remotes:')}`);
  if (entry.remotes.length === 0) {
    console.log('  (none)');
  } else {
    for (const remote of entry.remotes) {
      console.log(`  ${pc.cyan(remote.name)}`);
      console.log(`    fetch: ${remote.fetchUrl}`);
      console.log(`    push:  ${remote.pushUrl}`);
    }
  }

  // Local Branches
  console.log(`${pc.bold('Local Branches:')}`);
  if (entry.localBranches.length === 0) {
    console.log('  (none)');
  } else {
    for (const branch of entry.localBranches) {
      if (branch === entry.currentBranch) {
        console.log(`  ${pc.green('* ' + branch)}`);
      } else {
        console.log(`    ${branch}`);
      }
    }
  }

  // Remote Branches
  console.log(`${pc.bold('Remote Branches:')}`);
  if (entry.remoteBranches.length === 0) {
    console.log('  (none)');
  } else {
    for (const branch of entry.remoteBranches) {
      console.log(`    ${branch}`);
    }
  }

  // Current Branch
  console.log(`${pc.bold('Current Branch:')}   ${pc.green(entry.currentBranch)}`);

  // Last Updated
  console.log(`${pc.bold('Last Updated:')}     ${entry.lastUpdated}`);

  // User Description section
  console.log();
  if (entry.userDescription) {
    console.log(pc.bold('--- User Description ---'));
    console.log(entry.userDescription);
  } else {
    console.log(`${pc.bold('User Description:')} (none -- run 'gitter user-desc' to add)`);
  }

  // Description section
  console.log();
  if (entry.description) {
    console.log(pc.bold('--- Description ---'));
    console.log(pc.bold('Business Description:'));
    console.log(entry.description.businessDescription);
    console.log();
    console.log(pc.bold('Technical Description:'));
    console.log(entry.description.technicalDescription);
    console.log(`${pc.bold('Description Generated:')} ${entry.description.generatedAt}`);
    console.log(`${pc.bold('Generated By:')} ${entry.description.generatedBy}`);
    if (entry.description.instructions) {
      console.log(`${pc.bold('Instructions Used:')} ${entry.description.instructions}`);
    }
  } else {
    console.log(`${pc.bold('Description:')} (none -- run 'gitter describe' to generate)`);
  }

  // Tags section
  console.log();
  if (entry.tags && entry.tags.length > 0) {
    console.log(pc.bold('--- Tags ---'));
    console.log('  ' + entry.tags.map(t => pc.cyan(t)).join(', '));
  } else {
    console.log(`${pc.bold('Tags:')} (none -- run 'gitter tag --add <tag>' to add)`);
  }

  // Claude Sessions section
  console.log();
  if (entry.claudeSessions && entry.claudeSessions.length > 0) {
    console.log(pc.bold('--- Claude Sessions ---'));
    const sorted = [...entry.claudeSessions].sort(
      (a, b) => new Date(a.collectedAt).getTime() - new Date(b.collectedAt).getTime(),
    );
    for (const session of sorted) {
      const date = new Date(session.collectedAt);
      const formatted = date.toLocaleString();
      console.log(`  ${pc.cyan(session.sessionId)}  ${pc.dim(formatted)}`);
    }
  } else {
    console.log(`${pc.bold('Claude Sessions:')} (none -- run 'gitter remember-claude' to save)`);
  }

  // Notes section
  console.log();
  if (entry.notes) {
    console.log(pc.bold('--- Notes ---'));
    console.log(entry.notes);
  } else {
    console.log(`${pc.bold('Notes:')} (none -- run 'gitter notes' to add)`);
  }
  console.log();
}
